---
version: 2
triggers: [ ]

plan:
  project-key: CL
  key: TTE
  name: TrustTunnel - Deploy

stages:
  - Build artifacts:
      manual: false
      final: false
      jobs:
        - Build on Linux
        # - Build on macOS
  - Deploy artifacts:
      manual: false
      final: false
      jobs:
        - Deploy artifacts

Build on Linux:
  key: BL
  docker:
    image: adguard/core-libs:2.6
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            ENDPOINT_ROOT=${PWD}

            # Build for x86_64 (use musl for static binaries)
            CC=x86_64-linux-musl-gcc \
            CXX=x86_64-linux-musl-g++ \
            CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=x86_64-linux-musl-gcc \
            BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/opt/cross/x86_64-linux-musl" \
            cargo build --release --target x86_64-unknown-linux-musl

            # Build for aarch64 (use musl for static binaries)
            CC=aarch64-linux-musl-gcc \
            CXX=aarch64-linux-musl-g++ \
            CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-musl-gcc \
            BINDGEN_EXTRA_CLANG_ARGS="--sysroot=/opt/cross/aarch64-linux-musl" \
            cargo build --release --target aarch64-unknown-linux-musl

            mkdir -p build_linux
            VERSION=$(cat endpoint/Cargo.toml | grep "version = " | head -n 1 | sed -e 's/version = "\(.*\)"/\1/')

            pushd target/aarch64-unknown-linux-musl/release/
              llvm-strip trusttunnel_endpoint
              llvm-strip setup_wizard
              cp ${ENDPOINT_ROOT}/LICENSE .
              cp ${ENDPOINT_ROOT}/scripts/trusttunnel.service.template .
              NAME=trusttunnel-v${VERSION}-linux-aarch64
              tar zcf ${NAME}.tar.gz --transform "s,^,${NAME}/," trusttunnel_endpoint setup_wizard LICENSE trusttunnel.service.template
              mv ${NAME}.tar.gz ${ENDPOINT_ROOT}/build_linux
            popd

            pushd target/x86_64-unknown-linux-musl/release/
              llvm-strip trusttunnel_endpoint
              llvm-strip setup_wizard
              cp ${ENDPOINT_ROOT}/LICENSE .
              cp ${ENDPOINT_ROOT}/scripts/trusttunnel.service.template .
              NAME=trusttunnel-v${VERSION}-linux-x86_64
              tar zcf ${NAME}.tar.gz --transform "s,^,${NAME}/," trusttunnel_endpoint setup_wizard LICENSE trusttunnel.service.template
              mv ${NAME}.tar.gz ${ENDPOINT_ROOT}/build_linux
            popd
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build for Linux
      location: build_linux
      pattern: 'trusttunnel-*.tar.gz'
      required: true
      shared: true

# Build on macOS:
#   key: BM
#   tasks:
#     - checkout:
#         description: Checkout Default Repository
#         force-clean-build: 'true'
#     - script:
#         interpreter: SHELL
#         scripts:
#           - |-
#             #!/bin/bash
#             set -x -e
#             cargo build --release --target x86_64-apple-darwin
#             cp target/x86_64-apple-darwin/release/trusttunnel_endpoint target/trusttunnel_endpoint.osx-x86_64
#   requirements:
#     - ephemeral
#     - image: registry.int.agrd.dev/macos/sequoia-build-agent-xcode16.1:latest
#   artifact-subscriptions: [ ]
#   artifacts:
#     - name: Build result macOS
#       location: target
#       pattern: 'trusttunnel_endpoint.osx-x86_64'
#       required: false
#       shared: true

Deploy artifacts:
  key: DA
  docker:
    image: adguard/core-libs:2.6
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - clean
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            printf "%b\n" "${bamboo_sshSecretKey}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            git config user.email "Bamboo"
            git config user.name "Bamboo"

            VERSION=$(cat endpoint/Cargo.toml | grep "version = " | head -n 1 | sed -e 's/version = "\(.*\)"/\1/')

            # Update version in install script and push tag
            sed -i -e "s/^version='[0-9\.]*'$/version='${VERSION}'/" scripts/install.sh
            git add scripts/install.sh
            git commit -m "Automatic increment version for install script"
            TAG=v${VERSION}
            git tag -d ${TAG} || true
            git tag ${TAG}
            git remote set-url origin "${bamboo_planRepository_1_repositoryUrl}"
            git push origin ${TAG}

            # TODO: change to bamboo_githubPublicRepoPassword when repo become public
            git clone https://${bamboo_githubPrivateRepoPassword}:@github.com/TrustTunnel/TrustTunnel/
            cd TrustTunnel
            CHANGELOG_URL="https://github.com/TrustTunnel/TrustTunnel/blob/${TAG}/CHANGELOG.md"
            # TODO: change to bamboo_githubPublicRepoPassword when repo become public
            gh config set -h github.com oauth_token "${bamboo_githubPrivateRepoPassword}" || exit 1
            gh release delete -y ${TAG} || true
            gh release create ${TAG} -t "${TAG}" -n "See [CHANGELOG.md](${CHANGELOG_URL}) for the list of changes."
            gh release upload ${TAG} ../build_linux/trusttunnel-v${VERSION}-linux-x86_64.tar.gz
            gh release upload ${TAG} ../build_linux/trusttunnel-v${VERSION}-linux-aarch64.tar.gz
  requirements:
    - adg-privileged-docker
  artifact-subscriptions:
    - artifact: Build for Linux
      destination: build_linux
  artifacts: []

repositories:
  - core-libs/vpn-libs-endpoint:
      scope: global

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: [ ]

labels: [ ]

other:
  concurrent-build-plugin: system-default
